# This file configures the build and deployment settings for Netlify.

[build]
  # This command is run to build your site.
  # It installs dependencies and then runs the "build" script from your package.json.
  command = "npm run build"

  # This is the directory that contains the final, built version of your site.
  # It must match the --dist-dir specified in your build script.
  publish = "publish"

  # This is the directory where your serverless functions are located.
  functions = "netlify/functions/"
